# 1

## What is AI?
... to allow computers to learn from experience and understand the world in terms of a hierarchy of concepts, with each concept defined through its relation to simpler concepts.

Avoid the need for human operators to formally specify all the knowledge that the computer needs.

The hierachy of concepts enables the computer to learn complicated concepts by building them out of simpler ones.

## What is Machine Learning
In lieu of hard-coded knowledge, extract patterns from raw data to make decisions that appear subjective. (pg 3)

Dependent of the representation of data, known as features. Structure == performance.<br>
Manual feature engineering can be replaced by **representational learning**. This is great for adapting to new tasks. (pg 4)

**representational learning** -- example of **autoencoders**, used to convert input to and from new representations which have optimal qualities for ML algos.

Most important thing is disentanlging *factors of variation* -- separate sources of influence, and figuring out which abstract factors are most important (despite context).

## What is Deep Learning
Deep learning is great for this task, because it views complex representations as simpler concepts such as corners, contours (pg 5).<br>
Depth enables the computer to learn a multi-step computer program.

Specifically DL is a particular type of ML that has power and flexability by representing the world as a nested hierarchy of concepts, with each concept defined in relation to cimpler concepts and more abstract representations computed in terms of less abstraact ones.

## 2

## Linear Alg

How to we solve Ax = b ?
Where A is a matrix of real numbers, b is a known vector, and x is an unknown vector?

In [17]:
import numpy as np

In [281]:
A = np.matrix( [[1,2,3],[11,12,13],[21,22,23]]) 
b = np.matrix( [[1],[2],[3]] )             

In [205]:
A

matrix([[ 1,  2,  3],
        [11, 12, 13],
        [21, 22, 23]])

In [206]:
b

matrix([[1],
        [2],
        [3]])

### Some basic functions:

Transpose

In [128]:
A.T

matrix([[ 1, 11, 21],
        [ 2, 12, 22],
        [ 3, 13, 23]])

Inversion

In [203]:
A.I

matrix([[ 1.        ,  0.        ,  0.        ],
        [ 0.        ,  0.25      ,  0.        ],
        [ 0.        ,  0.        ,  0.16666667]])

dot product

In [209]:
A * b

matrix([[ 14],
        [ 74],
        [134]])

## Let's solve for x 
and double check that Ax = b 

In [91]:
b

matrix([[1],
        [2],
        [3]])

this is not equal to to x!! because of limited precision.

In [78]:
not_x = A.I * b
not_x

matrix([[-0.125],
        [-0.5  ],
        [ 0.75 ]])

Close, but no cigar!

In [211]:
A * not_x

matrix([[ 1.125],
        [ 2.375],
        [ 3.625]])

Use the linalg solve function instead!

In [210]:
x = np.linalg.solve(A, b) 
x

matrix([[-0.0231405 ],
        [-0.65371901],
        [ 0.7768595 ]])

this looks just like b

In [87]:
np.dot(A, x) 

matrix([[ 1.],
        [ 2.],
        [ 3.]])

Note the following functions are equivalent

In [199]:
assert np.array_equal(np.dot(A, x), A * x)

In [200]:
assert np.array_equal(np.dot(A, x), A.dot(x))

We can check the solution using allclose.

In [70]:
np.allclose(np.dot(A, x), b)

True

### Identity Matrixes
All zeros with 1 as diagonal.

In [116]:
I3 = np.identity(3)
I3

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

Supposedly A<sup>-1</sup> A = I<sub>n</sub>

In [232]:
np.dot(A.I,  A)

matrix([[-0.9375, -0.125 , -1.3125],
        [ 4.5   ,  1.    ,  1.5   ],
        [-1.25  ,  0.5   ,  1.25  ]])

Not sure why I can't re-create this!

## Special kinds of Matrices and Vectors

### Diagonal Matrix 
All not diag values are 0. Very efficient for multiplications. Identity matrix is an example.

In [179]:
A = np.matrix([[1,0,0],[0,4,0],[0,0,6]]) 
A

matrix([[1, 0, 0],
        [0, 4, 0],
        [0, 0, 6]])

### symmetric matrix
A<sup>T</sup> = A

In [177]:
A = np.matrix([[1,7,3],[7,4,-5],[3,-5,6]]) 
A

matrix([[ 1,  7,  3],
        [ 7,  4, -5],
        [ 3, -5,  6]])

In [135]:
np.array_equal(A.T, A)

True

### orthogonal vectors

In [140]:
x = np.array([2, 18])
y = np.array([3/2, -1/6])

x<sup>T</sup> y = 0

In [176]:
np.dot(x.T, y)

0.0

### orthogonal matrix

In [178]:
A = np.matrix([[2, -2, 1], [1, 2, 2], [2, 1, -2]]) / 3
np.round(A, 2)

array([[ 0.67, -0.67,  0.33],
       [ 0.33,  0.67,  0.67],
       [ 0.67,  0.33, -0.67]])

The dot product of A and A<sup>T</sup> is an identity marrix<br>
 A A<sup>T</sup> = I <sub>n</sub>

In [173]:
np.round(np.dot(A, A.T), 2)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

A<sup>-1</sup>= A<sup>T</sup>

In [172]:
np.array_equal(np.round(A.T, 2), np.round(A.I, 2))

True

## Matrix Decomposition

### Eigen Decomposition

In [286]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

### Eigenvectors and EigenValues

In [307]:
from scipy.linalg import eigh

eigen_val, eigen_vec = eigh(A, b=None, eigvals_only=False)

In [327]:
eigen_val, eigen_vec = np.linalg.eig(A)

Notice that we get a tuple for the eigenvalue, which should be a scalar.

In [462]:
eigen_val.shape

(2,)

In [463]:
eigen_vec.shape

(2, 2)

This equation should hold...

Av = &lambda;v

Where <br>
&lambda; is an eigenvalue<br>
v is a eigenvector

In [469]:
for lam, v in zip(eigen_val, eigen_vec.T):
    print("for eigenvalue:   {}\nand eigenvector: {}".format(lam, v))
    
    left = np.dot(A, v)
    right = lam * v
    
    print("The equation is {}\n".format(
            np.array_equal(np.round(left, 2), 
                           np.round(right, 2))))

for eigenvalue:   -0.3722813232690143
and eigenvector: [-0.82456484  0.56576746]
The equation is True

for eigenvalue:   5.372281323269014
and eigenvector: [-0.41597356 -0.90937671]
The equation is True

